### ISSUE TITLE
Stuck on Fetching current IP...

### ISSUE THREAD

**Issue by zolarious** [susmithHCK/torghost#4] opened 2017-01-16 08:08 UTC
when running, it gets stuck on Fetching current IP...
I think the tor relays some how is blocked, I am in saudi arabia, they do that 
is there any solution?

**Comment by misterbee2856** [comment] 2017-01-23 18:50
me too...
is there any solution..?

**Comment by zolarious** [comment] 2017-01-25 09:00
I found what was wrong with mine
I was trying to run it from a live usb kali linux, which most of it's packages including tor needed to be updated
so I have switched to persistent mode updated all the packages 
simply by writing these commands in terminal
apt-get update
apt-get upgrade 
apt-get dist-upgrade
then installed tor by this command: 
apt-get install tor 
then downloaded torghost, installed it and voi la tor is working, torghost is working too

**Comment by jmfgdev** [comment] 2017-04-09 02:49
For me the issue is trying to run torghost start kills my dns servers, after that I can't resolve even google.com, @susmithHCK I'd really appreciate if you could help me troubleshoot this.

**Comment by arismelachroinos** [comment] 2017-04-17 18:12
i have the same problem and i can't fix it. Can you help me?

**Comment by jmfgdev** [comment] 2017-04-17 18:31
I have a fork of this project where I'm trying to solve this specific issue maybe you guys could come help out? @zolarious @arismelachroinos 

So far I think the issue is how tor is installed by the script.

It should probably just do apt install tor but it does something else.

**Comment by jmfgdev** [comment] 2017-04-17 18:32
this is the method it uses to install TOR

`sudo apt-get install tor -y -qq`

**Comment by arismelachroinos** [comment] 2017-04-17 18:46
hes i saw that, but i dont think its wrong, it worked in the past

**Comment by jmfgdev** [comment] 2017-04-17 18:48
as you can see by how @zolarious fixed his problem you see he also used apt(-get) install tor
without the extra settings. A lot of things in this program work if removed too by the way.
In my fork i considered removing the line that tries to change network addressing here.

`VirtualAddrNetwork 10.0.0.0/10`

Not sure why it does this but this is one of the things that don't need to be there for it to work.

**Comment by susmithHCK** [comment] 2017-04-19 18:13
Sorry for the late reply. I suggest not to use any other dns server, because its will lead to DNSleak.
You can edit the script to make it work for you IP configuration. Here this is fot 192.168.1.0/24 network. Change that to what ever network you wanna use like VMware virtual network(192.34.0.0/24 or whatever ).

**Comment by jmfgdev** [comment] 2017-04-19 21:21
@susmithHCK Unfortunately TorGhost in it's current state completely leaks DNS requests outside the TOR network. It can't resolve .onion addresses and all the DNS Servers are those that were already on the computer. So when user's install your program @susmithHCK they will already be leaking their DNS requests 100%.

Thats why I made my fork when i noticed the problem.

The script here doesn't actually do anything with TorDNS. It simply leaks all DNS requests.
However by adding this line. The DNS leak was fixed in my fork.
https://github.com/jmfgdev/torghost/blob/master/torghost#L78
`AutomapHostsSuffixes .exit,.onion`

The script had not been configured to use TorDNS or connect to .onions. I'm not sure if you need the .exit part. But the script simply hides your ipv4 address and leaks all your DNS requests and can't connect to Tor Hidden Services or TorDNS.

**Comment by jmfgdev** [comment] 2017-04-19 21:28
I would like to also take this moment to warn anyone who used this script to anonymize themselves and didn't check and notice the full DNS leak before they browed. There was 100% a DNS leak so whatever DNS servers the computer you ran it on was what the sites you visited can see. So any site you browsed with the susmithHCK's version (Not my fork, it hides DNS) could easily what your DNS servers are, so if your DNS servers are that of your ISP. You may be in some trouble, or not. Hopefully everyone is OK. But just remember for the time being susmithHCK/torghost is a currently BROKEN anonymizing program. I'm working on my fork. I've already fixed the full DNS leak and gotten TorDNS to kick in. However, i'm still stuck on the fetching current IP on some machines. It seems that the solution for this problem is very evasive and is probably part of the OS it is being run on maybe not the script itself.

**Comment by susmithHCK** [comment] 2017-04-21 06:41
Nope every single packet is sent via tor. There are toomany dns leak testing site you can see it yourself.

**Comment by susmithHCK** [comment] 2017-04-21 06:43
However to acces hidden sites you have to add this line "AutomapHostsSuffixes .exit,.onion"

**Comment by jmfgdev** [comment] 2017-04-21 07:41
@susmithHCK Unfortunately it was said testing with dns leak testing sites that I realized that this repo doesn't route all traffic thru TOR. I don't know what is different in your setup but on multiple systems the DNS was 100% leaked. There is no doubt about this. I even had people using my fork and yours to test which one routed all traffic thru TOR. I wouldn't have made a whole fork if the program already routed every single packet thru TOR.

**Comment by blackdream0** [comment] 2017-06-12 01:27
![screenshot 167](https://user-images.githubusercontent.com/29075500/27016332-f26d466c-4f1e-11e7-9b0c-6308b77bfb96.png)
can any one solve this problem please

**Comment by jmfgdev** [comment] 2017-06-12 11:54
@blackdream0 the author doesn't believe me that there is a mistake in how DNS is routed thru TOR, its unlikely it will ever be fixed

**Comment by blackdream0** [comment] 2017-06-13 22:27
how to uninstall this

**Closed** 2017-08-02 10:26 UTC
